### ISSUE TITLE
Crash After exporting the Project

### ISSUE THREAD

**Issue by owstetra** [SIsilicon/Godot-Planar-Reflection-Plugin#1]
Windows 7 x64bit
Hi ! This is really Great Work !
But there is an Issue with it , it Crash after exporting the project

Export the Same project provided by Plugin and see

**Comment by SIsilicon** [comment]
To what platform are you exporting it too?

**Comment by owstetra** [comment]
Sorry , i Updated the comment , it's on Windows

**Comment by SIsilicon** [comment]
I checked back my project and discovered that it crashes even when I disable the add-on and remove the Planar reflector.

**Comment by SIsilicon** [comment]
I'll have to do some more tests, but I'm currently focused on a couple other projects. Have you tried using the add-on in a different project and exporting that one?

**Comment by owstetra** [comment]
Yes , i tried it in other projects and the same issue happen , it keep crashing

**Comment by SIsilicon** [comment]
It should be fixed now. :)
https://github.com/SIsilicon/Godot-Planar-Reflection-Plugin/releases/tag/v1.1.0

**Comment by owstetra** [comment]
It's Working now !!
Thank you !!
