### ISSUE TITLE
Request license change

### ISSUE THREAD

**Issue by Hevedy** [SIsilicon/Godot-Planar-Reflection-Plugin#3]
The GPL license isn't usable for a plugin where the engine is MIT on purpose for it, and this cancels the rest of license and public/private projects freedom.

So what about switch it to MIT or ZLIB or something alike please?

Thank you.

**Comment by SIsilicon** [comment]
Done. 👍

**Comment by Hevedy** [comment]
Thank you so much \o/

**Comment by Moonwards** [comment]
Yes indeed thank you \o/
